import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;

public class AdminPaneli extends javax.swing.JFrame {

    private static int kullaniciId;
    YemekMenusu yemekMenusu = new YemekMenusu();
    KullaniciYonetimi kullaniciYonetimi = new KullaniciYonetimi();
    OdemeTakibi odeme = new OdemeTakibi();

    /**
     * Creates new form AdminPaneli
     *
     * @param KullaniciId
     */
    public AdminPaneli(int KullaniciId) {
        initComponents();
        setLocationRelativeTo(null);
        AdminPaneli.kullaniciId = KullaniciId;
        tabloyuDoldur(yemekMenusuTable, "Menuler");
        tabloyuDoldur(kullaniciYonetimiTable, "Kullanicilar");
        tabloyuDoldur(odemeTakibiTable, "Odemeler");
        satirGetirYemek();
        satirGetirKullanici();
        satirGetirOdeme();
    }

    private static void tabloyuDoldur(JTable doldurulacakTable, String tabloAdi) {

        String query = "SELECT * FROM " + tabloAdi;

        try (Connection conn = DbHelper.getConnection(); Statement stmt = conn.createStatement(); ResultSet rs = stmt.executeQuery(query)) {

            DefaultTableModel model = new DefaultTableModel();
            ResultSetMetaData meta = rs.getMetaData();
            int kolonSayisi = meta.getColumnCount();

            for (int i = 1; i <= kolonSayisi; i++) {
                model.addColumn(meta.getColumnName(i));
            }

            while (rs.next()) {
                Object[] row = new Object[kolonSayisi];
                for (int i = 1; i <= kolonSayisi; i++) {
                    row[i - 1] = rs.getObject(i);
                }
                model.addRow(row);
            }

            doldurulacakTable.setModel(model);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void satirGetirKullanici() {
        kullaniciYonetimiTable.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && kullaniciYonetimiTable.getSelectedRow() != -1) {
                int selectedRow = kullaniciYonetimiTable.getSelectedRow();
                idTXT.setText(kullaniciYonetimiTable.getValueAt(selectedRow, 0).toString());
                tcNoTXT.setText(kullaniciYonetimiTable.getValueAt(selectedRow, 1).toString());
                adTXT.setText(kullaniciYonetimiTable.getValueAt(selectedRow, 2).toString());
                soyadTXT.setText(kullaniciYonetimiTable.getValueAt(selectedRow, 3).toString());
                sifreTXT.setText(kullaniciYonetimiTable.getValueAt(selectedRow, 4).toString());
                rolTXT.setText(kullaniciYonetimiTable.getValueAt(selectedRow, 5).toString());

            }
        });
    }

    
    private void satirGetirYemek() {
        yemekMenusuTable.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && yemekMenusuTable.getSelectedRow() != -1) {
                int selectedRow = yemekMenusuTable.getSelectedRow();
                menuIdTXT.setText(yemekMenusuTable.getValueAt(selectedRow, 0).toString());
                tarihTXT.setText(yemekMenusuTable.getValueAt(selectedRow, 1).toString());
                anaYemekTXT.setText(yemekMenusuTable.getValueAt(selectedRow, 2).toString());
                yanYemekTXT.setText(yemekMenusuTable.getValueAt(selectedRow, 3).toString());
                corbaTXT.setText(yemekMenusuTable.getValueAt(selectedRow, 4).toString());
                tatliTXT.setText(yemekMenusuTable.getValueAt(selectedRow, 5).toString());

            }
        });
    }
    
    private void satirGetirOdeme() {
        odemeTakibiTable.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && odemeTakibiTable.getSelectedRow() != -1) {
                int selectedRow = odemeTakibiTable.getSelectedRow();
                odemeIdTXT.setText(odemeTakibiTable.getValueAt(selectedRow, 0).toString());
                kullaniciIdTXT.setText(odemeTakibiTable.getValueAt(selectedRow, 1).toString());
                miktarTXT.setText(odemeTakibiTable.getValueAt(selectedRow, 2).toString());
                islemTarihiTXT.setText(odemeTakibiTable.getValueAt(selectedRow, 3).toString());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        yemekMenusuPanel = new javax.swing.JPanel();
        yemekMenusuSP = new javax.swing.JScrollPane();
        yemekMenusuTable = new javax.swing.JTable();
        corbaTXT = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        menuIdTXT = new javax.swing.JTextField();
        tatliTXT = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tarihTXT = new javax.swing.JTextField();
        anaYemekTXT = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        yanYemekTXT = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        yAraBTN = new javax.swing.JButton();
        yTemizleBTN = new javax.swing.JButton();
        yEkleBTN = new javax.swing.JButton();
        ySilBTN = new javax.swing.JButton();
        yGuncelleBTN = new javax.swing.JButton();
        yListeleBTN = new javax.swing.JButton();
        kullaniciYonetimiPanel = new javax.swing.JPanel();
        kullaniciYonetimiSP = new javax.swing.JScrollPane();
        kullaniciYonetimiTable = new javax.swing.JTable();
        idTXT = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tcNoTXT = new javax.swing.JTextField();
        adTXT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        soyadTXT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sifreTXT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rolTXT = new javax.swing.JTextField();
        kAraBTN = new javax.swing.JButton();
        kTemizleBTN = new javax.swing.JButton();
        kEkleBTN = new javax.swing.JButton();
        kSilBTN = new javax.swing.JButton();
        kGuncelleBTN = new javax.swing.JButton();
        kListeleBTN = new javax.swing.JButton();
        odemeTakipPanel = new javax.swing.JPanel();
        odemeTakibiSP = new javax.swing.JScrollPane();
        odemeTakibiTable = new javax.swing.JTable();
        kullaniciIdTXT = new javax.swing.JTextField();
        miktarTXT = new javax.swing.JTextField();
        odemeIdTXT = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        islemTarihiTXT = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        oEkleBTN = new javax.swing.JButton();
        oSilBTN = new javax.swing.JButton();
        oListeleBTN = new javax.swing.JButton();
        oGuncelleBTN = new javax.swing.JButton();
        oAraBTN = new javax.swing.JButton();
        oTemizleBTN = new javax.swing.JButton();
        geriDonBTN = new javax.swing.JButton();
        kullanicilarGitBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setForeground(new java.awt.Color(255, 204, 204));

        yemekMenusuPanel.setBackground(new java.awt.Color(255, 204, 255));
        yemekMenusuPanel.setForeground(new java.awt.Color(255, 153, 153));

        yemekMenusuTable.setBackground(new java.awt.Color(204, 204, 255));
        yemekMenusuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        yemekMenusuSP.setViewportView(yemekMenusuTable);

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Tatlı:");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Menü Id:");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Tarih:");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Ana Yemek:");

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Yan Yemek:");

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Çorba:");

        yAraBTN.setBackground(new java.awt.Color(204, 204, 255));
        yAraBTN.setForeground(new java.awt.Color(0, 0, 0));
        yAraBTN.setText("Ara");
        yAraBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yAraBTNActionPerformed(evt);
            }
        });

        yTemizleBTN.setBackground(new java.awt.Color(204, 204, 255));
        yTemizleBTN.setForeground(new java.awt.Color(0, 0, 0));
        yTemizleBTN.setText("Temizle");
        yTemizleBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yTemizleBTNActionPerformed(evt);
            }
        });

        yEkleBTN.setBackground(new java.awt.Color(204, 204, 255));
        yEkleBTN.setForeground(new java.awt.Color(0, 0, 0));
        yEkleBTN.setText("Ekle");
        yEkleBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yEkleBTNActionPerformed(evt);
            }
        });

        ySilBTN.setBackground(new java.awt.Color(204, 204, 255));
        ySilBTN.setForeground(new java.awt.Color(0, 0, 0));
        ySilBTN.setText("Sil");
        ySilBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ySilBTNActionPerformed(evt);
            }
        });

        yGuncelleBTN.setBackground(new java.awt.Color(204, 204, 255));
        yGuncelleBTN.setForeground(new java.awt.Color(0, 0, 0));
        yGuncelleBTN.setText("Güncelle");
        yGuncelleBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yGuncelleBTNActionPerformed(evt);
            }
        });

        yListeleBTN.setBackground(new java.awt.Color(204, 204, 255));
        yListeleBTN.setForeground(new java.awt.Color(0, 0, 0));
        yListeleBTN.setText("Listele");
        yListeleBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yListeleBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout yemekMenusuPanelLayout = new javax.swing.GroupLayout(yemekMenusuPanel);
        yemekMenusuPanel.setLayout(yemekMenusuPanelLayout);
        yemekMenusuPanelLayout.setHorizontalGroup(
            yemekMenusuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yemekMenusuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(yemekMenusuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yemekMenusuSP, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                    .addGroup(yemekMenusuPanelLayout.createSequentialGroup()
                        .addGroup(yemekMenusuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(yemekMenusuPanelLayout.createSequentialGroup()
                                .addGroup(yemekMenusuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addGap(34, 34, 34)
                                .addGroup(yemekMenusuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tarihTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(menuIdTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(yemekMenusuPanelLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(anaYemekTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(yemekMenusuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(yemekMenusuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tatliTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(corbaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yanYemekTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(yemekMenusuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(yEkleBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(yGuncelleBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(yAraBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(yemekMenusuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(yListeleBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ySilBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(yTemizleBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        yemekMenusuPanelLayout.setVerticalGroup(
            yemekMenusuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yemekMenusuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(yemekMenusuSP, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(yemekMenusuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(yemekMenusuPanelLayout.createSequentialGroup()
                        .addGroup(yemekMenusuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(menuIdTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(yemekMenusuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tarihTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(yemekMenusuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(anaYemekTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(yemekMenusuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(yemekMenusuPanelLayout.createSequentialGroup()
                            .addComponent(ySilBTN)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(yListeleBTN)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(yTemizleBTN))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, yemekMenusuPanelLayout.createSequentialGroup()
                            .addComponent(yEkleBTN)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(yGuncelleBTN)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(yAraBTN)))
                    .addGroup(yemekMenusuPanelLayout.createSequentialGroup()
                        .addGroup(yemekMenusuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yanYemekTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(yemekMenusuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(corbaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(yemekMenusuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tatliTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Yemek Menüsü", yemekMenusuPanel);

        kullaniciYonetimiPanel.setBackground(new java.awt.Color(255, 204, 255));

        kullaniciYonetimiTable.setBackground(new java.awt.Color(204, 204, 255));
        kullaniciYonetimiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        kullaniciYonetimiSP.setViewportView(kullaniciYonetimiTable);

        idTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTXTActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Id:");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Tc No:");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Ad:");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Soyad:");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Şifre:");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Rol:");

        kAraBTN.setBackground(new java.awt.Color(204, 204, 255));
        kAraBTN.setForeground(new java.awt.Color(0, 0, 0));
        kAraBTN.setText("Ara");
        kAraBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kAraBTNActionPerformed(evt);
            }
        });

        kTemizleBTN.setBackground(new java.awt.Color(204, 204, 255));
        kTemizleBTN.setForeground(new java.awt.Color(0, 0, 0));
        kTemizleBTN.setText("Temizle");
        kTemizleBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kTemizleBTNActionPerformed(evt);
            }
        });

        kEkleBTN.setBackground(new java.awt.Color(204, 204, 255));
        kEkleBTN.setForeground(new java.awt.Color(0, 0, 0));
        kEkleBTN.setText("Ekle");
        kEkleBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kEkleBTNActionPerformed(evt);
            }
        });

        kSilBTN.setBackground(new java.awt.Color(204, 204, 255));
        kSilBTN.setForeground(new java.awt.Color(0, 0, 0));
        kSilBTN.setText("Sil");
        kSilBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kSilBTNActionPerformed(evt);
            }
        });

        kGuncelleBTN.setBackground(new java.awt.Color(204, 204, 255));
        kGuncelleBTN.setForeground(new java.awt.Color(0, 0, 0));
        kGuncelleBTN.setText("Güncelle");
        kGuncelleBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kGuncelleBTNActionPerformed(evt);
            }
        });

        kListeleBTN.setBackground(new java.awt.Color(204, 204, 255));
        kListeleBTN.setForeground(new java.awt.Color(0, 0, 0));
        kListeleBTN.setText("Listele");
        kListeleBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kListeleBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kullaniciYonetimiPanelLayout = new javax.swing.GroupLayout(kullaniciYonetimiPanel);
        kullaniciYonetimiPanel.setLayout(kullaniciYonetimiPanelLayout);
        kullaniciYonetimiPanelLayout.setHorizontalGroup(
            kullaniciYonetimiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kullaniciYonetimiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kullaniciYonetimiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kullaniciYonetimiPanelLayout.createSequentialGroup()
                        .addComponent(kullaniciYonetimiSP)
                        .addContainerGap())
                    .addGroup(kullaniciYonetimiPanelLayout.createSequentialGroup()
                        .addGroup(kullaniciYonetimiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(kullaniciYonetimiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(adTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(soyadTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(kullaniciYonetimiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(kullaniciYonetimiPanelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rolTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kullaniciYonetimiPanelLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sifreTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kullaniciYonetimiPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(36, 36, 36)
                                .addComponent(tcNoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(kullaniciYonetimiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kEkleBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kGuncelleBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kAraBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kullaniciYonetimiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(kListeleBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(kSilBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kTemizleBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(13, 13, 13))))
        );
        kullaniciYonetimiPanelLayout.setVerticalGroup(
            kullaniciYonetimiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kullaniciYonetimiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kullaniciYonetimiSP, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kullaniciYonetimiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(kullaniciYonetimiPanelLayout.createSequentialGroup()
                        .addComponent(idTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kullaniciYonetimiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kullaniciYonetimiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(soyadTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(kullaniciYonetimiPanelLayout.createSequentialGroup()
                        .addGroup(kullaniciYonetimiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tcNoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kullaniciYonetimiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sifreTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kullaniciYonetimiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rolTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(kullaniciYonetimiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(kullaniciYonetimiPanelLayout.createSequentialGroup()
                            .addComponent(kSilBTN)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(kListeleBTN)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(kTemizleBTN))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kullaniciYonetimiPanelLayout.createSequentialGroup()
                            .addComponent(kEkleBTN)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(kGuncelleBTN)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(kAraBTN))))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Kullanıcı Yönetimi", kullaniciYonetimiPanel);

        odemeTakipPanel.setBackground(new java.awt.Color(255, 204, 255));
        odemeTakipPanel.setForeground(new java.awt.Color(255, 153, 153));

        odemeTakibiTable.setBackground(new java.awt.Color(204, 204, 255));
        odemeTakibiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        odemeTakibiSP.setViewportView(odemeTakibiTable);

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Kullanıcı Id:");

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("İşlem Tarihi");

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Miktar:");

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Ödeme Id:");

        oEkleBTN.setBackground(new java.awt.Color(204, 204, 255));
        oEkleBTN.setForeground(new java.awt.Color(0, 0, 0));
        oEkleBTN.setText("Ekle");
        oEkleBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oEkleBTNActionPerformed(evt);
            }
        });

        oSilBTN.setBackground(new java.awt.Color(204, 204, 255));
        oSilBTN.setForeground(new java.awt.Color(0, 0, 0));
        oSilBTN.setText("Sil");
        oSilBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oSilBTNActionPerformed(evt);
            }
        });

        oListeleBTN.setBackground(new java.awt.Color(204, 204, 255));
        oListeleBTN.setForeground(new java.awt.Color(0, 0, 0));
        oListeleBTN.setText("Listele");
        oListeleBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oListeleBTNActionPerformed(evt);
            }
        });

        oGuncelleBTN.setBackground(new java.awt.Color(204, 204, 255));
        oGuncelleBTN.setForeground(new java.awt.Color(0, 0, 0));
        oGuncelleBTN.setText("Güncelle");
        oGuncelleBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oGuncelleBTNActionPerformed(evt);
            }
        });

        oAraBTN.setBackground(new java.awt.Color(204, 204, 255));
        oAraBTN.setForeground(new java.awt.Color(0, 0, 0));
        oAraBTN.setText("Ara");
        oAraBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oAraBTNActionPerformed(evt);
            }
        });

        oTemizleBTN.setBackground(new java.awt.Color(204, 204, 255));
        oTemizleBTN.setForeground(new java.awt.Color(0, 0, 0));
        oTemizleBTN.setText("Temizle");
        oTemizleBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oTemizleBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout odemeTakipPanelLayout = new javax.swing.GroupLayout(odemeTakipPanel);
        odemeTakipPanel.setLayout(odemeTakipPanelLayout);
        odemeTakipPanelLayout.setHorizontalGroup(
            odemeTakipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(odemeTakipPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(odemeTakipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(odemeTakibiSP, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, odemeTakipPanelLayout.createSequentialGroup()
                        .addGroup(odemeTakipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel16))
                        .addGap(34, 34, 34)
                        .addGroup(odemeTakipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kullaniciIdTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(odemeIdTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(odemeTakipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(odemeTakipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(islemTarihiTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(miktarTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(odemeTakipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(oEkleBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(oGuncelleBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(oAraBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(odemeTakipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(oListeleBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(oSilBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(oTemizleBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        odemeTakipPanelLayout.setVerticalGroup(
            odemeTakipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(odemeTakipPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(odemeTakibiSP, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(odemeTakipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(odemeTakipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(odemeTakipPanelLayout.createSequentialGroup()
                            .addComponent(oSilBTN)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(oListeleBTN)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(oTemizleBTN))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, odemeTakipPanelLayout.createSequentialGroup()
                            .addComponent(oEkleBTN)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(oGuncelleBTN)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(oAraBTN)))
                    .addGroup(odemeTakipPanelLayout.createSequentialGroup()
                        .addGroup(odemeTakipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(odemeTakipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(odemeIdTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16))
                            .addGroup(odemeTakipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(miktarTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15)))
                        .addGap(18, 18, 18)
                        .addGroup(odemeTakipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(odemeTakipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(kullaniciIdTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13))
                            .addGroup(odemeTakipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(islemTarihiTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14)))))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ödeme Takibi", odemeTakipPanel);

        geriDonBTN.setBackground(new java.awt.Color(204, 204, 255));
        geriDonBTN.setForeground(new java.awt.Color(0, 0, 0));
        geriDonBTN.setText("Geri Dön");
        geriDonBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriDonBTNActionPerformed(evt);
            }
        });

        kullanicilarGitBTN.setBackground(new java.awt.Color(204, 204, 255));
        kullanicilarGitBTN.setForeground(new java.awt.Color(0, 0, 0));
        kullanicilarGitBTN.setText("Kullanıcılar Paneline Git");
        kullanicilarGitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullanicilarGitBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(kullanicilarGitBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(geriDonBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(geriDonBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kullanicilarGitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTXTActionPerformed

    private void yGuncelleBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yGuncelleBTNActionPerformed
        // TODO add your handling code here:
        yemekMenusu.setMenuID(menuIdTXT.getText());
        yemekMenusu.setTarih(tarihTXT.getText());
        yemekMenusu.setAnaYemek(anaYemekTXT.getText());
        yemekMenusu.setYanYemek(yanYemekTXT.getText());
        yemekMenusu.setCorba(corbaTXT.getText());
        yemekMenusu.setTatli(tatliTXT.getText());

        yemekMenusu.Guncelle();
        yemekMenusuTable.setModel((DefaultTableModel) yemekMenusu.Listele());
    }//GEN-LAST:event_yGuncelleBTNActionPerformed

    private void kGuncelleBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kGuncelleBTNActionPerformed
        // TODO add your handling code here:
        kullaniciYonetimi.setId(idTXT.getText());
        kullaniciYonetimi.setTc(tcNoTXT.getText());
        kullaniciYonetimi.setAd(adTXT.getText());
        kullaniciYonetimi.setSoyad(soyadTXT.getText());
        kullaniciYonetimi.setSifre(sifreTXT.getText());
        kullaniciYonetimi.setRol(rolTXT.getText());

        kullaniciYonetimi.Guncelle();
        kullaniciYonetimiTable.setModel((DefaultTableModel) kullaniciYonetimi.Listele());
    }//GEN-LAST:event_kGuncelleBTNActionPerformed

    private void yEkleBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yEkleBTNActionPerformed
        // TODO add your handling code here:
        yemekMenusu.setTarih(tarihTXT.getText());
        yemekMenusu.setAnaYemek(anaYemekTXT.getText());
        yemekMenusu.setYanYemek(yanYemekTXT.getText());
        yemekMenusu.setCorba(corbaTXT.getText());
        yemekMenusu.setTatli(tatliTXT.getText());

        yemekMenusu.Ekle();
        yemekMenusuTable.setModel((DefaultTableModel) yemekMenusu.Listele());
    }//GEN-LAST:event_yEkleBTNActionPerformed

    private void kEkleBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kEkleBTNActionPerformed
        // TODO add your handling code here:
        kullaniciYonetimi.setTc(tcNoTXT.getText());
        kullaniciYonetimi.setAd(adTXT.getText());
        kullaniciYonetimi.setSoyad(soyadTXT.getText());
        kullaniciYonetimi.setSifre(sifreTXT.getText());
        kullaniciYonetimi.setRol(rolTXT.getText());

        kullaniciYonetimi.Ekle();
        kullaniciYonetimiTable.setModel((DefaultTableModel) kullaniciYonetimi.Listele());
    }//GEN-LAST:event_kEkleBTNActionPerformed

    private void kSilBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kSilBTNActionPerformed
        // TODO add your handling code here:
        kullaniciYonetimi.setId(idTXT.getText());
        kullaniciYonetimi.Sil();
        kullaniciYonetimiTable.setModel((DefaultTableModel) kullaniciYonetimi.Listele());
    }//GEN-LAST:event_kSilBTNActionPerformed

    private void ySilBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ySilBTNActionPerformed
        // TODO add your handling code here:
        yemekMenusu.setMenuID(menuIdTXT.getText());

        yemekMenusu.Sil();
        yemekMenusuTable.setModel((DefaultTableModel) yemekMenusu.Listele());
    }//GEN-LAST:event_ySilBTNActionPerformed

    private void yListeleBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yListeleBTNActionPerformed
        // TODO add your handling code here:
        yemekMenusuTable.setModel((DefaultTableModel) yemekMenusu.Listele());
    }//GEN-LAST:event_yListeleBTNActionPerformed

    private void kListeleBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kListeleBTNActionPerformed
        // TODO add your handling code here:
        kullaniciYonetimiTable.setModel((DefaultTableModel) kullaniciYonetimi.Listele());
    }//GEN-LAST:event_kListeleBTNActionPerformed

    private void kAraBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kAraBTNActionPerformed
        // TODO add your handling code here:
        kullaniciYonetimi.setId(idTXT.getText());
        kullaniciYonetimi.setTc(tcNoTXT.getText());
        kullaniciYonetimi.setAd(adTXT.getText());
        kullaniciYonetimi.setSoyad(soyadTXT.getText());
        kullaniciYonetimi.setSifre(sifreTXT.getText());
        kullaniciYonetimi.setRol(rolTXT.getText());

        kullaniciYonetimi.Ara(kullaniciYonetimiTable);
    }//GEN-LAST:event_kAraBTNActionPerformed

    private void yAraBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yAraBTNActionPerformed
        // TODO add your handling code here:
        yemekMenusu.setMenuID(menuIdTXT.getText());
        yemekMenusu.setTarih(tarihTXT.getText());
        yemekMenusu.setAnaYemek(anaYemekTXT.getText());
        yemekMenusu.setYanYemek(yanYemekTXT.getText());
        yemekMenusu.setCorba(corbaTXT.getText());
        yemekMenusu.setTatli(tatliTXT.getText());

        yemekMenusu.Ara(yemekMenusuTable);
    }//GEN-LAST:event_yAraBTNActionPerformed

    private void yTemizleBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yTemizleBTNActionPerformed
        // TODO add your handling code here:
        menuIdTXT.setText("");
        tarihTXT.setText("");
        anaYemekTXT.setText("");
        yanYemekTXT.setText("");
        corbaTXT.setText("");
        tatliTXT.setText("");
    }//GEN-LAST:event_yTemizleBTNActionPerformed

    private void kTemizleBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kTemizleBTNActionPerformed
        // TODO add your handling code here:
        idTXT.setText("");
        tcNoTXT.setText("");
        adTXT.setText("");
        soyadTXT.setText("");
        sifreTXT.setText("");
        rolTXT.setText("");
    }//GEN-LAST:event_kTemizleBTNActionPerformed

    private void kullanicilarGitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullanicilarGitBTNActionPerformed
        // TODO add your handling code here:
        JFrame thisFrame = this;
        thisFrame.setEnabled(false);

        KullanicilarPaneli kullanicilarP = new KullanicilarPaneli(kullaniciId);
        kullanicilarP.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        kullanicilarP.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                thisFrame.setEnabled(true);
                thisFrame.toFront();
            }
        });

        kullanicilarP.setVisible(true);
    }//GEN-LAST:event_kullanicilarGitBTNActionPerformed

    private void geriDonBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriDonBTNActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        girisEkrani GirisEkrani = new girisEkrani();
        GirisEkrani.setVisible(true);
    }//GEN-LAST:event_geriDonBTNActionPerformed

    private void oEkleBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oEkleBTNActionPerformed
        // TODO add your handling code here:
        odeme.setKullaniciID(kullaniciIdTXT.getText());
        odeme.setMiktar(miktarTXT.getText());
        odeme.setIslemTarihi(islemTarihiTXT.getText());

        odeme.Ekle();
        odemeTakibiTable.setModel((DefaultTableModel) odeme.Listele());
    }//GEN-LAST:event_oEkleBTNActionPerformed

    private void oSilBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oSilBTNActionPerformed
        // TODO add your handling code here:
        odeme.setOdemeID(odemeIdTXT.getText());

        odeme.Sil();
        odemeTakibiTable.setModel((DefaultTableModel) odeme.Listele());
    }//GEN-LAST:event_oSilBTNActionPerformed

    private void oListeleBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oListeleBTNActionPerformed
        // TODO add your handling code here:
        odemeTakibiTable.setModel((DefaultTableModel) odeme.Listele());
    }//GEN-LAST:event_oListeleBTNActionPerformed

    private void oGuncelleBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oGuncelleBTNActionPerformed
        // TODO add your handling code here:
        odeme.setOdemeID(odemeIdTXT.getText());
        odeme.setKullaniciID(kullaniciIdTXT.getText());
        odeme.setMiktar(miktarTXT.getText());
        odeme.setIslemTarihi(islemTarihiTXT.getText());

        odeme.Guncelle();
        odemeTakibiTable.setModel((DefaultTableModel) odeme.Listele());
    }//GEN-LAST:event_oGuncelleBTNActionPerformed

    private void oAraBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oAraBTNActionPerformed
        // TODO add your handling code here:
        odeme.setOdemeID(odemeIdTXT.getText());
        odeme.setKullaniciID(kullaniciIdTXT.getText());
        odeme.setMiktar(miktarTXT.getText());
        odeme.setIslemTarihi(islemTarihiTXT.getText());

        odemeTakibiTable.setModel((DefaultTableModel) odeme.Ara());
    }//GEN-LAST:event_oAraBTNActionPerformed

    private void oTemizleBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oTemizleBTNActionPerformed
        // TODO add your handling code here:
        odemeIdTXT.setText("");
        kullaniciIdTXT.setText("");
        miktarTXT.setText("");
        islemTarihiTXT.setText("");
    }//GEN-LAST:event_oTemizleBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AdminPaneli(kullaniciId).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adTXT;
    private javax.swing.JTextField anaYemekTXT;
    private javax.swing.JTextField corbaTXT;
    private javax.swing.JButton geriDonBTN;
    private javax.swing.JTextField idTXT;
    private javax.swing.JTextField islemTarihiTXT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton kAraBTN;
    private javax.swing.JButton kEkleBTN;
    private javax.swing.JButton kGuncelleBTN;
    private javax.swing.JButton kListeleBTN;
    private javax.swing.JButton kSilBTN;
    private javax.swing.JButton kTemizleBTN;
    private javax.swing.JTextField kullaniciIdTXT;
    private javax.swing.JPanel kullaniciYonetimiPanel;
    private javax.swing.JScrollPane kullaniciYonetimiSP;
    private javax.swing.JTable kullaniciYonetimiTable;
    private javax.swing.JButton kullanicilarGitBTN;
    private javax.swing.JTextField menuIdTXT;
    private javax.swing.JTextField miktarTXT;
    private javax.swing.JButton oAraBTN;
    private javax.swing.JButton oEkleBTN;
    private javax.swing.JButton oGuncelleBTN;
    private javax.swing.JButton oListeleBTN;
    private javax.swing.JButton oSilBTN;
    private javax.swing.JButton oTemizleBTN;
    private javax.swing.JTextField odemeIdTXT;
    private javax.swing.JScrollPane odemeTakibiSP;
    private javax.swing.JTable odemeTakibiTable;
    private javax.swing.JPanel odemeTakipPanel;
    private javax.swing.JTextField rolTXT;
    private javax.swing.JTextField sifreTXT;
    private javax.swing.JTextField soyadTXT;
    private javax.swing.JTextField tarihTXT;
    private javax.swing.JTextField tatliTXT;
    private javax.swing.JTextField tcNoTXT;
    private javax.swing.JButton yAraBTN;
    private javax.swing.JButton yEkleBTN;
    private javax.swing.JButton yGuncelleBTN;
    private javax.swing.JButton yListeleBTN;
    private javax.swing.JButton ySilBTN;
    private javax.swing.JButton yTemizleBTN;
    private javax.swing.JTextField yanYemekTXT;
    private javax.swing.JPanel yemekMenusuPanel;
    private javax.swing.JScrollPane yemekMenusuSP;
    private javax.swing.JTable yemekMenusuTable;
    // End of variables declaration//GEN-END:variables
}
