import java.sql.*;
import java.time.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class KullanicilarPaneli extends javax.swing.JFrame {

    private static int kullaniciID;

    /**
     * Creates new form KullanicilarPaneli
     *
     * @param kullaniciId
     */

    public KullanicilarPaneli(int kullaniciId) {
        initComponents();
        setLocationRelativeTo(null);
        KullanicilarPaneli.kullaniciID = kullaniciId;

        gunlukBakiyeYukleBTN.addActionListener(e -> bakiyeYukle(25.0));
        miktarliBakiyeYukleBTN.addActionListener(e -> miktarliYukleme());
        
        haftalikGoster();
        bakiyeGoster();
    }
    
    private void haftalikGoster() {
        LocalDate simdi = LocalDate.now();
        LocalDate pazartesi = simdi.with(DayOfWeek.MONDAY);
        LocalDate cuma = simdi.with(DayOfWeek.FRIDAY);

        String sql = "SELECT tarih, anaYemek, yanYemek, corba, tatli FROM Menuler WHERE tarih BETWEEN ? AND ? ORDER BY tarih ASC";

        try (Connection conn = DbHelper.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setDate(1, java.sql.Date.valueOf(pazartesi));
            stmt.setDate(2, java.sql.Date.valueOf(cuma));

            ResultSet rs = stmt.executeQuery();

            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("tarih");
            model.addColumn("anaYemek");
            model.addColumn("yanYemek");
            model.addColumn("corba");
            model.addColumn("tatli");

            while (rs.next()) {
                Object[] row = {
                    rs.getDate("tarih"),
                    rs.getString("anaYemek"),
                    rs.getString("yanYemek"),
                    rs.getString("corba"),
                    rs.getString("tatli")
                };
                model.addRow(row);
            }

            haftalikMenuTable.setModel(model);

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void bakiyeGoster() {
        try (Connection conn = DbHelper.getConnection(); PreparedStatement stmt = conn.prepareStatement("SELECT bakiye FROM Bakiye WHERE kullaniciID = ?")) {
            stmt.setInt(1, kullaniciID);
            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                double bakiye = rs.getDouble("bakiye");
                bakiyeLabel.setText("Bakiye: " + bakiye + " ₺");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    private void bakiyeYukle(double miktar) {
        try (Connection conn = DbHelper.getConnection(); PreparedStatement stmt = conn.prepareStatement("UPDATE Bakiye SET bakiye = bakiye + ? WHERE kullaniciID = ?")) {
            stmt.setDouble(1, miktar);
            stmt.setInt(2, kullaniciID);
            stmt.executeUpdate();
            bakiyeGoster();
            JOptionPane.showMessageDialog(this, miktar + " ₺ yüklendi.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    private void miktarliYukleme() {
        String input = JOptionPane.showInputDialog(this, "Yüklenecek miktarı girin:");
        if (input != null) {
            try {
                double miktar = Double.parseDouble(input);
                if (miktar > 0) {
                    bakiyeYukle(miktar);
                } else {
                    JOptionPane.showMessageDialog(this, "Geçerli bir miktar giriniz.");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Geçersiz sayı formatı.");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bakiyeLabel = new javax.swing.JLabel();
        gunlukBakiyeYukleBTN = new javax.swing.JButton();
        miktarliBakiyeYukleBTN = new javax.swing.JButton();
        haftalikMenuSP = new javax.swing.JScrollPane();
        haftalikMenuTable = new javax.swing.JTable();
        cikisBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        geriDonBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        bakiyeLabel.setForeground(new java.awt.Color(0, 0, 0));
        bakiyeLabel.setText("Bakiye:.....");

        gunlukBakiyeYukleBTN.setBackground(new java.awt.Color(255, 204, 255));
        gunlukBakiyeYukleBTN.setForeground(new java.awt.Color(0, 0, 0));
        gunlukBakiyeYukleBTN.setText("Günlük Yükle");
        gunlukBakiyeYukleBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gunlukBakiyeYukleBTNActionPerformed(evt);
            }
        });

        miktarliBakiyeYukleBTN.setBackground(new java.awt.Color(255, 204, 255));
        miktarliBakiyeYukleBTN.setForeground(new java.awt.Color(0, 0, 0));
        miktarliBakiyeYukleBTN.setText("Miktar Girerek Yükle");
        miktarliBakiyeYukleBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miktarliBakiyeYukleBTNActionPerformed(evt);
            }
        });

        haftalikMenuSP.setBackground(new java.awt.Color(204, 204, 255));
        haftalikMenuSP.setForeground(new java.awt.Color(0, 0, 0));

        haftalikMenuTable.setBackground(new java.awt.Color(255, 204, 255));
        haftalikMenuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        haftalikMenuSP.setViewportView(haftalikMenuTable);

        cikisBTN.setBackground(new java.awt.Color(255, 204, 255));
        cikisBTN.setForeground(new java.awt.Color(0, 0, 0));
        cikisBTN.setText("Çıkış");
        cikisBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisBTNActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Bu Haftaki Yemek Menüsü");

        geriDonBTN.setBackground(new java.awt.Color(204, 204, 255));
        geriDonBTN.setForeground(new java.awt.Color(0, 0, 0));
        geriDonBTN.setText("Geri Dön");
        geriDonBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriDonBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bakiyeLabel)
                .addGap(192, 192, 192)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(gunlukBakiyeYukleBTN)
                        .addGap(40, 40, 40)
                        .addComponent(miktarliBakiyeYukleBTN)
                        .addGap(18, 18, 18)
                        .addComponent(cikisBTN))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                        .addComponent(geriDonBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(haftalikMenuSP, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(geriDonBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 254, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gunlukBakiyeYukleBTN)
                    .addComponent(bakiyeLabel)
                    .addComponent(miktarliBakiyeYukleBTN)
                    .addComponent(cikisBTN))
                .addGap(11, 11, 11))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(haftalikMenuSP, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(57, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gunlukBakiyeYukleBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gunlukBakiyeYukleBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gunlukBakiyeYukleBTNActionPerformed

    private void miktarliBakiyeYukleBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miktarliBakiyeYukleBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miktarliBakiyeYukleBTNActionPerformed

    private void cikisBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisBTNActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cikisBTNActionPerformed

    private void geriDonBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriDonBTNActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        girisEkrani GirisEkrani = new girisEkrani();
        GirisEkrani.setVisible(true);
    }//GEN-LAST:event_geriDonBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KullanicilarPaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KullanicilarPaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KullanicilarPaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KullanicilarPaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new KullanicilarPaneli(kullaniciID).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bakiyeLabel;
    private javax.swing.JButton cikisBTN;
    private javax.swing.JButton geriDonBTN;
    private javax.swing.JButton gunlukBakiyeYukleBTN;
    private javax.swing.JScrollPane haftalikMenuSP;
    private javax.swing.JTable haftalikMenuTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton miktarliBakiyeYukleBTN;
    // End of variables declaration//GEN-END:variables
}
